# Generated by Django 5.0.6 on 2024-07-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='wage_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
